function renderReports(){const s=activeStudy(),root=$('#reportsContent');if(!s){const p=portfolio();root.innerHTML=`<div class="card reportbox">COSTLAB CALCULATOR - SYNTHÈSE PORTEFEUILLE\n\nÉtudes actives : ${state.studies.filter(x=>x.status!=='Archivée').length}\nBudget direct total : ${fmt(p.direct)}\nCoût complet total : ${fmt(p.full)}\nFinancements : ${fmt(p.funded)}\nDépenses : ${fmt(p.spent)}</div>`;return}const c=calcStudy(s),txt=`COSTLAB CALCULATOR - RAPPORT BUDGÉTAIRE\n\nÉtude : ${s.name}${s.code?' ('+s.code+')':''}\nStatut : ${s.status}\nN analysable cible : ${s.targetN}\nPassations estimées : ${c.required}\nSessions estimées : ${c.sessions}\n\nBUDGET DIRECT\nParticipants : ${fmt(c.participants)}\nConsommables : ${fmt(c.consumables)}\nServices : ${fmt(c.services)}\nDéplacements : ${fmt(c.travel)}\nBudget direct total : ${fmt(c.direct)}\n\nCOÛT COMPLET\nPersonnel : ${fmt(c.personnel)}\nMatériel : ${fmt(c.equipment)}\nFrais indirects : ${fmt(c.overhead)}\nCoût complet total : ${fmt(c.full)}\nCoût par participant analysable : ${fmt(c.costPerValid)}\n\nSUIVI\nFinancements déclarés : ${fmt(c.funded)}\nDépenses réelles : ${fmt(c.spent)}\nReste financé : ${fmt(c.remainingFunds)}\n\nGénéré le ${new Date().toLocaleString()}`;root.innerHTML=`<div class="card reportbox" id="reportText">${esc(txt)}</div>`}
function renderSettings(){applySettings()}
function renderAll(){applySettings();renderSelector();renderDashboard();renderStudies();renderCompare();renderParticipants();renderBudgetTables();renderScenario();renderReports();}

function selectStudy(id){state.activeStudyId=id==='__all__'?null:id;localStorage.setItem(APP_KEY,JSON.stringify(state));renderAll();if(id!=='__all__')goPage('participants')}
function goPage(page){currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));$$('#nav button[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#sidebar').classList.remove('open');if(page==='reports')renderReports();if(page==='scenarios')renderScenario()}
function openStudyDialog(id=null){editingStudyId=id;const s=id?state.studies.find(x=>x.id===id):defaultStudy(`Étude ${state.studies.length+1}`),f=$('#studyForm');$('#studyDialogTitle').textContent=id?'Modifier l’étude':'Nouvelle étude';['name','code','status','startDate','endDate','targetN','validN','exclusionRate','dropoutRate','techLossRate','pilotN','sessionsPerParticipant','compensation','sessionMinutes','overheadRate','description'].forEach(k=>f.elements[k].value=s[k]??'');f.elements.tags.value=(s.tags||[]).join(', ');$('#studyDialog').showModal()}
function editStudy(id){openStudyDialog(id)}
function duplicateStudy(id){const s=state.studies.find(x=>x.id===id);if(!s)return;const c=JSON.parse(JSON.stringify(s));c.id=uid();c.name=s.name+' - copie';c.code='';c.status='Planifiée';c.validN=0;c.expenses=[];c.orders=[];c.scenarios=[];c.createdAt=new Date().toISOString();state.studies.push(c);state.activeStudyId=c.id;save();toast('Étude dupliquée')}
function archiveStudy(id){const s=state.studies.find(x=>x.id===id);if(!s)return;s.status=s.status==='Archivée'?'Planifiée':'Archivée';if(s.id===state.activeStudyId&&s.status==='Archivée')state.activeStudyId=state.studies.find(x=>x.status!=='Archivée'&&x.id!==s.id)?.id||null;save()}
function deleteScenario(id){const s=activeStudy();s.scenarios=s.scenarios.filter(x=>x.id!==id);save()}
