const schemas={
 consumables:{title:'Consommable',fields:[['name','Nom','text'],['mode','Mode','select',['session','fixed']],['packagePrice','Prix du conditionnement','number'],['packageQty','Quantité par conditionnement','number'],['useQty','Quantité utilisée / session','number'],['stockQty','Stock disponible','number'],['unit','Unité','text'],['supplier','Fournisseur','text'],['reference','Référence','text'],['fundable','Éligible financement','checkbox']]},
 personnel:{title:'Personnel',fields:[['role','Rôle','text'],['hourly','Coût horaire','number'],['fixedHours','Heures fixes','number'],['hoursPerSession','Heures / session','number'],['includeDirect','Inclure au budget direct','checkbox'],['includeFull','Inclure au coût complet','checkbox']]},
 equipment:{title:'Matériel',fields:[['name','Équipement','text'],['mode','Mode','select',['purchase','rental','amortized']],['price','Prix / valeur','number'],['years','Durée amortissement (ans)','number'],['sharePct','Part imputée à l’étude (%)','number'],['maintenance','Maintenance / consommables fixes','number'],['includeDirect','Inclure au budget direct','checkbox'],['includeFull','Inclure au coût complet','checkbox']]},
 services:{title:'Service / autre coût',fields:[['name','Poste','text'],['category','Catégorie','text'],['amount','Montant','number'],['fundable','Éligible financement','checkbox'],['notes','Notes','textarea']]},
 travel:{title:'Déplacement',fields:[['name','Poste','text'],['category','Catégorie','select',['Transport','Hébergement','Repas','Mission','Autre']],['amount','Montant','number'],['fundable','Éligible financement','checkbox'],['notes','Notes','textarea']]},
 funding:{title:'Financement',fields:[['name','Source','text'],['amount','Montant','number'],['reference','Référence / centre de coût','text'],['notes','Notes','textarea']]},
 expenses:{title:'Dépense',fields:[['date','Date','date'],['name','Poste','text'],['category','Catégorie','text'],['amount','Montant','number'],['status','Statut','select',['Prévu','Engagé','Payé']],['reference','Référence','text']]},
 orders:{title:'Commande',fields:[['name','Article','text'],['qty','Quantité','number'],['amount','Prix estimé','number'],['supplier','Fournisseur','text'],['reference','Référence','text'],['status','Statut','select',['À commander','Demandé','Commandé','Reçu','Annulé']]]}
};