$('#studyForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),obj=editingStudyId?state.studies.find(s=>s.id===editingStudyId):defaultStudy();['name','code','status','startDate','endDate','description'].forEach(k=>obj[k]=fd.get(k)||'');['targetN','validN','exclusionRate','dropoutRate','techLossRate','pilotN','sessionsPerParticipant','compensation','sessionMinutes','overheadRate'].forEach(k=>obj[k]=n(fd.get(k)));obj.tags=String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean);if(!editingStudyId)state.studies.push(obj);state.activeStudyId=obj.id;$('#studyDialog').close();save();toast('Étude enregistrée')});
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const s=activeStudy(),schema=schemas[itemType],fd=new FormData(e.currentTarget),obj=editingItemId?s[itemType].find(x=>x.id===editingItemId):{id:uid()};schema.fields.forEach(([k,l,t])=>{obj[k]=t==='checkbox'?e.currentTarget.elements[k].checked:t==='number'?n(fd.get(k)):fd.get(k)||''});if(!editingItemId)s[itemType].push(obj);$('#itemDialog').close();save();toast('Ligne enregistrée')});

$$('[data-open-study]').forEach(b=>b.onclick=()=>openStudyDialog());$('#quickAddStudy').onclick=()=>openStudyDialog();$$('[data-add-item]').forEach(b=>b.onclick=()=>openItem(b.dataset.addItem));
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b)goPage(b.dataset.page)});$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#studySelector').onchange=e=>selectStudy(e.target.value);$('#studySearch').oninput=renderStudies;$('#studyStatusFilter').onchange=renderStudies;
$('#langBtn').onclick=()=>{state.settings.lang=state.settings.lang==='fr'?'en':'fr';save()};$('#themeBtn').onclick=()=>{state.settings.theme=state.settings.theme==='light'?'dark':'light';save()};
[['setTheme','theme'],['setAccent','accent'],['setLang','lang'],['setScale','scale'],['setCurrency','currency']].forEach(([id,k])=>$('#'+id).onchange=e=>{state.settings[k]=e.target.value;save()});[['setContrast','contrast'],['setDyslexia','dyslexia'],['setMotion','motion']].forEach(([id,k])=>$('#'+id).onchange=e=>{state.settings[k]=e.target.checked;save()});
$('#collapseSidebar').onclick=()=>{const collapsed=getComputedStyle(document.documentElement).getPropertyValue('--sidebar').trim()==='78px';document.documentElement.style.setProperty('--sidebar',collapsed?'268px':'78px');$('#sidebar .brand div:nth-child(2)').classList.toggle('hidden',!collapsed);$$('#nav span,#nav .group,.side-footer small,.side-footer button').forEach(x=>x.classList.toggle('hidden',!collapsed))};
$('#generateOrders').onclick=()=>{const s=activeStudy();if(!s)return;const generated=[];(s.consumables||[]).forEach(x=>{if(x.mode==='fixed')return;const need=n(x.useQty)*sessions(s),missing=Math.max(0,need-n(x.stockQty));if(missing>0){const packs=Math.ceil(missing/Math.max(1,n(x.packageQty)));generated.push({id:uid(),name:x.name,qty:packs,amount:packs*n(x.packagePrice),supplier:x.supplier||'',reference:x.reference||'',status:'À commander'})}});s.orders=[...(s.orders||[]),...generated];save();toast(`${generated.length} ligne(s) ajoutée(s)`) };
$('#saveScenario').onclick=()=>{const s=activeStudy();if(!s)return;const name=prompt('Nom du scénario',`Scénario ${(s.scenarios||[]).length+1}`);if(!name)return;const override=scenarioOverride(),result=calcStudy(s,override);s.scenarios.push({id:uid(),name,override,result,createdAt:new Date().toISOString()});save();toast('Scénario enregistré')};
$('#copyReport').onclick=async()=>{const txt=$('#reportText')?.innerText||$('#reportsContent').innerText;await navigator.clipboard.writeText(txt);toast('Rapport copié')};
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(rows){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';return rows.map(r=>r.map(q).join(';')).join('\n')}
$('#exportJson').onclick=()=>download(`costlab-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');$('#dashExport').onclick=$('#exportJson').onclick;
$('#importJson').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.studies))throw Error();state=data;save();toast('Sauvegarde importée')}catch{alert('Fichier JSON invalide')}};
$('#exportSummaryCsv').onclick=()=>download('costlab-studies.csv',csv([['Study','Code','Status','Target N','Required N','Direct budget','Full cost','Funding','Spent'],...state.studies.map(s=>{const c=calcStudy(s);return[s.name,s.code,s.status,s.targetN,c.required,c.direct,c.full,c.funded,c.spent]})]),'text/csv');
$('#exportBudgetCsv').onclick=()=>{const s=activeStudy();if(!s)return;const c=calcStudy(s);download(`${s.code||s.name}-budget.csv`,csv([['Category','Amount'],['Participants',c.participants],['Consumables',c.consumables],['Personnel',c.personnel],['Equipment',c.equipment],['Services',c.services],['Travel',c.travel],['Overhead',c.overhead],['Direct budget',c.direct],['Full cost',c.full]]),'text/csv')};
$('#exportExpensesCsv').onclick=()=>{const s=activeStudy();if(!s)return;download(`${s.code||s.name}-expenses.csv`,csv([['Date','Name','Category','Amount','Status','Reference'],...(s.expenses||[]).map(x=>[x.date,x.name,x.category,x.amount,x.status,x.reference])]),'text/csv')};
$('#makeSnapshot').onclick=()=>{localStorage.setItem(SNAP_KEY,JSON.stringify(state));toast('Instantané créé')};$('#restoreSnapshot').onclick=()=>{const x=localStorage.getItem(SNAP_KEY);if(x){state=JSON.parse(x);save();toast('Instantané restauré')}};$('#resetAll').onclick=()=>{if(confirm('Réinitialiser toutes les données ?')){state=demoState();save();toast('Données réinitialisées')}};